apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      module: backend
  template:
    metadata:
      labels:
        module: backend
    spec:

      initContainers:
        - name: wait-for-db
          image: postgres:18.1-alpine
          env:
            - name: PGPASSWORD
              value: "password"
          command:
            - sh
            - -c
            - |
              echo "Waiting for database..."
              until pg_isready -h database-svc -p 5432 -U postgres; do
                sleep 2
              done
              echo "Database is ready."

      containers:
        - name: backend
          image: artisantek/kubecoin-backend:1.0
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "database-svc"
            - name: DB_NAME
              value: "kubecoin"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"
