apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: prod
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30144
  selector:
    module: frontend     